site_name: Modular API
theme:
  name: material

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition:
  - toc:
      permalink: true
  - meta:
  - def_list:
  - pymdownx.details:
  - pymdownx.superfences:
  - pymdownx.tabbed:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.caret:
  - pymdownx.mark:
  - pymdownx.tilde:
