site_name: Modular API
theme:
  name: material
  palette:
    primary: light blue

repo_url: https://github.com/Modular-Lab/Modular-API
edit_uri: edit/main/doc/docs/

extra_css:
  - stylesheets/extra.css


nav:
  - Welcome to ModularAPI: index.md
  - Concept: concept.md
  - Setting: setting.md
  - Command Line Interface:
    - init: cli/init.md
    - modules: cli/modules.md
    - db: cli/db.md
  - FAQ:
    - todo: faq/todo.md
  - Roadmap:
    - TO-DO: roadmap/todo.md
    - Update: roadmap/update.md



markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list: 
  - admonition:
  - toc:
      permalink: true
  - meta:
  - def_list:
  - pymdownx.details:
  - pymdownx.superfences:
  - pymdownx.tabbed:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.caret:
  - pymdownx.mark:
  - pymdownx.tilde:
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg