name: mkdocs build

on:
  push:
    branches:
    - 'main'
    paths:
    - 'doc/**'
  
  pull_request:
    branches:
    - 'main'
    paths:
    - 'doc/**'

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.16
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: doc/mkdocs.yml
          EXTRA_PACKAGES: build-base
          
